Repository knative-sandbox/eventing-couchdb, pull requests merged in 2020-11, with the labels that each got.

#19 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/performance-tests.sh
  vendor/knative.dev/pkg/reconciler/testing/reactions.go
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#20 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#21 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#22 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/L

#24 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/adapter/v2/main_message.go
  vendor/knative.dev/eventing/pkg/kncloudevents/http_client.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#23 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/S

#25 Fix a few more occurrences of divisive language
  source/config/placeholder.go
Labels: approved, cla: yes, lgtm, size/XS

#26 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/sinkbinding_lifecycle.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info_matchers.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info_store.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_log.go
  vendor/knative.dev/eventing/test/lib/recordevents/receiver/receiver.go
  vendor/knative.dev/eventing/test/lib/recordevents/receiver/reply.go
  vendor/knative.dev/eventing/test/lib/recordevents/recorder_vent/constructor.go
  vendor/knative.dev/eventing/test/lib/recordevents/recorder_vent/recorder.go
  vendor/knative.dev/eventing/test/lib/recordevents/resources.go
  vendor/knative.dev/eventing/test/lib/recordevents/sender/sender.go
  vendor/knative.dev/eventing/test/lib/sender/resources.go
  vendor/knative.dev/eventing/test/test_images/recordevents/main.go
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/reconciler/testing/tracker.go
  vendor/knative.dev/pkg/test/logging/.gitattributes
  vendor/knative.dev/pkg/test/logging/doc.go
  vendor/knative.dev/pkg/test/logging/error.go
  vendor/knative.dev/pkg/test/logging/logger.go
  vendor/knative.dev/pkg/test/logging/memory_encoder.go
  vendor/knative.dev/pkg/test/logging/spew_encoder.go
  vendor/knative.dev/pkg/test/logging/sugar.go
  vendor/knative.dev/pkg/test/logging/tlogger.go
  vendor/knative.dev/pkg/test/logging/zapr.go
  vendor/knative.dev/pkg/tracker/enqueue.go
  vendor/knative.dev/pkg/tracker/interface.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#27 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/adapter/v2/main.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/ping_conversion.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/doc.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_conversion.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_defaults.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/register.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/clientset.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/scheme/register.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1beta2/doc.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1beta2/generated_expansion.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1beta2/pingsource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1beta2/sources_client.go
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/hack/update-k8s-deps.sh
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/knative.dev/pkg/network/network.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#28 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#29 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/webhook/env.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#30 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#31 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/logconfig/config.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/spoof/request.go
  vendor/knative.dev/pkg/test/spoof/response_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#32 Get webhook name from common pkg
  source/cmd/webhook/main.go
  vendor/knative.dev/eventing/pkg/logconfig/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#33 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  source/pkg/client/injection/client/client.go
  vendor/knative.dev/hack/microbenchmarks.sh
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#34 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/ping_conversion.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L
