Repository knative-sandbox/eventing-couchdb, pull requests merged in 2020-10, with the labels that each got.

#11 Removed deprecated test images
  hack/tools.go
  vendor/knative.dev/eventing/test/test_images/filterevents/main.go
  vendor/knative.dev/eventing/test/test_images/filterevents/pod.yaml
  vendor/knative.dev/eventing/test/test_images/sequencestepper/main.go
  vendor/knative.dev/eventing/test/test_images/sequencestepper/pod.yaml
  vendor/knative.dev/eventing/test/test_images/transformevents/main.go
  vendor/knative.dev/eventing/test/test_images/transformevents/pod.yaml
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#13 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#16 [release-0.18] Upgrade to latest dependencies
  go.mod
  go.sum
  source/pkg/client/injection/reconciler/sources/v1alpha1/couchdbsource/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#18 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/S
