Repository knative-sandbox/eventing-couchdb, pull requests merged in 2021-06, with the labels that each got.

#110 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/S

#109 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/S

#106 Remove CODEOWNERS
  .github/CODEOWNERS
Labels: approved, cla: yes, lgtm, size/XS

#108 Update update-codegen
  hack/update-codegen.sh
Labels: approved, cla: yes, lgtm, size/M

#111 [main] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-vulnerability.yaml
Labels: approved, cla: yes, lgtm, size/M

#116 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#118 [main] Update actions
  .github/workflows/knative-go-test.yaml
Labels: approved, cla: yes, lgtm, size/XS

#117 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  source/pkg/client/clientset/versioned/fake/register.go
  source/pkg/client/listers/sources/v1alpha1/couchdbsource.go
  vendor/knative.dev/eventing/pkg/kncloudevents/retries.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#120 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS
