Repository knative-sandbox/eventing-couchdb, pull requests merged in 2021-08, with the labels that each got.

#131 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#129 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, lgtm, approved, size/XS

#132 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/S

#138 Use `controller.Impl` tracker and cleanups
  source/pkg/reconciler/controller.go
Labels: cla: yes, kind/cleanup, lgtm, approved, size/XS

#136 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: cla: yes, lgtm, approved, size/XS

#137 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/in_memory_channel_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/in_memory_channel_types.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/test/helpers/name.go
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: cla: yes, size/M, lgtm, approved

#133 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, lgtm, approved, size/S

#140 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, lgtm, approved, size/S
